name: Update version.json

on:
  schedule:
    - cron: '0 * * * *' # This will run the workflow once a day at midnight UTC

jobs:
  update_version_json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Update version.json
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PACKAGE_NAME: com.Beyondigitality.IdleWanderer
        run: python .github/scripts/update_version_json.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add version.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update version.json with the latest app version"
          git push
